### ISSUE TITLE
关于参数 T

### ISSUE THREAD

**Issue by luoxia-wen** [d9n13lt4n/timegan-pytorch#10]
请问，
如果以等长的时间序列输入到RNN，即max_seq_len=every_seq_len
还需要参数T吗？

**Comment by birdx0810** [comment]
不需要。

**Comment by luoxia-wen** [comment]
谢谢

**Comment by luoxia-wen** [comment]
关于recovery，官方实现源代码中与supervisor一样最后会经过sigmoid，作者给出的理由是：转换为与输入一样的【0，1】的区间
