### ISSUE TITLE
Minor code issue

### ISSUE THREAD

**Issue by kyugorithm** [d9n13lt4n/timegan-pytorch#3]
Thank you for your ‘pytorch’ implementation.
By the way, I faced some issues on ‘timegan.py’.
In the function(def _discriminator_forward(self, X, T, Z, gamma=1) ; 434 line, 
You coded H_hat is extracted from H using supervisor.
But I think H_hat should not be extracted from H, but from E_hat.
![image](https://user-images.githubusercontent.com/40943064/142819306-f867ec1c-85e0-471c-a721-f7e67ce30a46.png)  

(As defined in the original code)
Please check this issue.

Thank you

**Comment by ghost** [comment]
Nice catch, the code has been updated.

감사합니다~
