### ISSUE TITLE
Is "T" a static feature in code?

### ISSUE THREAD

**Issue by lijzijie** [d9n13lt4n/timegan-pytorch#5]
Thanks to your open code in pytorch, it was faster in trainning than tf1. And I have a question in paper and code, what is the static feature in code, is it "T"? In the code annotation: "T: the temporal information ", so that I think "T" is not the static feature, but if not, what is the static feature in code? How static feature precipitate in code? Thanks again！

**Comment by birdx0810** [comment]
T is the **sequence length** of the time-series. Static features are not used within the given dataset. As mentioned in this [comment](https://github.com/jsyoon0823/TimeGAN/issues/13#issuecomment-743923812) of the original implementation.

Whether if a feature is static or not is not defined within the code, but by the input data. A simple example could be a medical record, where features such as `age`, `height` are considered static, and features such as `heart_rate`, `respitory_rate` are considered as dynamic features.

Hopes this helps.

**Comment by lijzijie** [comment]
> 

Appreciate for your answer! So kinds of you, I understand it. While in another hand, the static and dynamic feature is the most import idea in paper, but why the author not implementation in the code? And would you give me some advice in implementation the static feature in code?

**Comment by birdx0810** [comment]
Well, I'm not one of the author's so I can't exactly give you an answer regarding that. For TimeGAN, the simplest way to integrate static and temporal features is by broadcasting the static features to have same length as your sequence length.

Example:
```
Age, Gender, HR, RR -> Age, Gender, HR, RR
40, 0, 72, 14           40, 0, 72, 14
       73, 15           40, 0, 73, 15
       72, 14           40, 0, 72, 14
```

**Comment by lijzijie** [comment]
> Well, I'm not one of the author's so I can't exactly give you an answer regarding that. However, the simplest way to integrate static and temporal features is by broadcasting the static features to have same length as your sequence length.
> 
> Example:
> 
> ```
> Age, Gender, HR, RR -> Age, Gender, HR, RR
> 40, 0, 72, 14           40, 0, 72, 14
>        73, 15           40, 0, 73, 15
>        72, 14           40, 0, 72, 14
> ```

Thanks for your patient answer!
