### ISSUE TITLE
data

### ISSUE THREAD

**Issue by ycm910** [d9n13lt4n/timegan-pytorch#6]
Hello, I have read the code, but I have a question, what's the difference between the data in this code and the TimeGAN ([Yoon et al., NIPS2019], how did you process the original data? hope you give a answer, thanks a lot.

**Comment by birdx0810** [comment]
> What's the difference between the data in this code and Yoon et al. (2019)

https://github.com/birdx0810/timegan-pytorch/issues/2

> How did I process the original?

Also similar to the original implementation.
